# **NumPy ufuncs**

## **ufuncs**

ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.


**Why use ufuncs?**

ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

where boolean array or condition defining where the operations should take place.

dtype defining the return type of elements.

out output array where the return value should be copied.

## **Vectorization**?

Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.



---



# **Create Your Own ufunc**

## **How To Create Your Own ufunc**

To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The **frompyfunc()** method takes the following arguments:
- function - the name of the function.
- inputs - the number of input arguments (arrays).
- outputs - the number of output arrays.

In [63]:
# import numPy

import numpy as np

In [64]:
def myadd(x, y):
  return x+y

sum = np.frompyfunc(myadd, 2, 1)

print(sum([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


## **Check if a Function is a ufunc**

Check the type of a function to check if it is a ufunc or not.

A ufunc should return <class 'numpy.ufunc'>.



In [65]:
print(type(np.add))

<class 'numpy.ufunc'>


If it is not a ufunc, it will return another type, like this built-in NumPy function for joining two or more arrays:

In [66]:
print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>



---



# **Simple Arithmetic**



You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.

Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.

All of the discussed arithmetic functions take a **where parameter** in which we can specify that condition.



In [67]:
arr1 = np.array([10, 11, 12, 13, 14, 15])

arr2 = np.array([3, 5, 6, 8, 2, 33])

## **Addition**

The add() function sums the content of two arrays, and return the results in a new array.

In [68]:
np.add(arr1, arr2)

array([13, 16, 18, 21, 16, 48])

## **Subtraction**

The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.



In [69]:
np.subtract(arr1, arr2)

array([  7,   6,   6,   5,  12, -18])

## **Multiplication**

The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.



In [70]:
np.multiply(arr1, arr2)

array([ 30,  55,  72, 104,  28, 495])

## **Division**

The divide() function divides the values from one array with the values from another array, and return the results in a new array.



In [71]:
np.divide(arr1, arr2)

array([3.33333333, 2.2       , 2.        , 1.625     , 7.        ,
       0.45454545])

## **Power**

The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

In [72]:
np.power(arr1, arr2)

array([                1000,               161051,              2985984,
                  815730721,                  196, -2081117049324899825])

## **Remainder**

Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.



In [73]:
np.mod(arr1, arr2)

array([ 1,  1,  0,  5,  0, 15])

In [74]:
np.remainder(arr1, arr2)

array([ 1,  1,  0,  5,  0, 15])

## **Quotient and Mod**

The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [75]:
np.divmod(arr1, arr2)

(array([3, 2, 2, 1, 7, 0]), array([ 1,  1,  0,  5,  0, 15]))

## **Absolute Values**

Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()



In [76]:
arr = np.array([-1, -4, 0, -2, 8, -57, 29])

np.absolute(arr)

array([ 1,  4,  0,  2,  8, 57, 29])

In [77]:
np.abs(arr)

array([ 1,  4,  0,  2,  8, 57, 29])



---



# **Rounding Decimals**

There are primarily five ways of rounding off decimals in NumPy:
- truncation
- fix
- rounding
- floor
- ceil


## **Truncation**

Remove the decimals, and return the float number closest to zero. Use the **trunc()** and **fix()** functions.



In [78]:
arr = np.trunc([-3.1666, 3.6667])

arr

array([-3.,  3.])

In [79]:
arr = np.fix([-3.1666, 3.6667])

arr

array([-3.,  3.])

## **Rounding**

The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

In [80]:
arr = np.around(3.1666, 2)

arr

np.float64(3.17)

In [81]:
arr = np.around(3.1666, 1)

arr

np.float64(3.2)

## **Floor**

The floor() function rounds off decimal to nearest lower integer.

In [82]:
arr = np.floor([-3.1666, 3.6667])

arr

array([-4.,  3.])

## **Ceil**

The ceil() function rounds off decimal to nearest upper integer.

In [83]:
arr = np.ceil([-3.1666, 3.6667])

arr

array([-3.,  4.])



---



# **Logs**

NumPy provides functions to perform log at the base 2, e and 10.

All of the log functions will place -inf or inf in the elements if the log can not be computed.



## **Log at Base 2**

Use the log2() function to perform log at the base 2.

In [84]:
arr = np.arange(1, 10)

np.log2(arr)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

**Note:** The arange(1, 10) function returns an array with integers starting from 1 (included) to 10 (not included).

## Log at Base 10

Use the log10() function to perform log at the base 10.

In [85]:
arr = np.arange(1, 10)

np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

## **Natural Log, or Log at Base e**

Use the log() function to perform log at the base e.

In [86]:
arr = np.arange(1, 10)

np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])



---



# **Summations**

Q. What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.

In [87]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

np.add(arr1, arr2)

array([2, 4, 6])

In [88]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print(np.sum([arr1, arr2]))

12


## **Summation Over an Axis**

If you specify axis=1, NumPy will sum the numbers in each array.

In [89]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis = 1)

newarr

array([6, 6])

In [90]:
# axis = 0 -> column

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis = 0)

newarr

array([2, 4, 6])

## **Cummulative Sum**

Cummulative sum means partially adding the elements in array.

Perfom partial sum with the **cumsum() function**.

In [91]:
arr = np.array([1, 2, 3])

np.cumsum(arr)

array([1, 3, 6])



---



# **Products**

To find the product of the elements in an array, use the prod() function.

In [92]:
arr = np.array([1, 2, 3, 4])

prod = np.prod(arr)

print(prod)

24


In [93]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


## **Product Over an Axis**

If you specify axis=1, NumPy will return the product of each array.

In [94]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


## **Cummulative Product**

Cummulative product means taking the product partially.

Perfom partial sum with the **cumprod() function**.



In [95]:
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]




---



# **Differences**

A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the **diff() function**.



In [96]:
arr = np.array([10, 15, 25, 5])

sub = np.diff(arr)

print(sub)

[  5  10 -20]


We can perform this operation repeatedly by giving parameter n.

E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]


In [97]:
arr = np.array([10, 15, 25, 5])

sub = np.diff(arr, n=2)

print(sub)

[  5 -30]




---



# **LCM - Lowest Common Multiple**

The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.

In [98]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


## **Finding LCM in Arrays**

To find the Lowest Common Multiple of all values in an array, you can use the **reduce() method**.

The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.

In [99]:
arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520




---



# **GCD - Greatest Common Divisor**

The GCD (Greatest Common Divisor), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.


In [100]:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


## **Finding GCD in Arrays**

To find the Highest Common Factor of all values in an array, you can use the reduce() method.

The reduce() method will use the ufunc, in this case the gcd() function, on each element, and reduce the array by one dimension.

In [101]:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4




---



# **Trigonometric Functions**

NumPy provides the ufuncs **sin(), cos() and tan()** that take values in radians and produce the corresponding sin, cos and tan values.

In [102]:
x = np.sin(np.pi/2)

print(x)

1.0


In [103]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


## **Convert Degrees Into Radians**

By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.

**Note:** radians values are pi/180 * degree_values.

In [104]:
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


## **Convert Radians to Degrees**



In [105]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


## **Finding Angles**

Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs **arcsin(), arccos() and arctan()** that produce radian values for corresponding sin, cos and tan values given.



In [106]:
x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [107]:
x = np.arccos(1.0)

print(x)

0.0


In [108]:
x = np.arctan(1.0)

print(x)

0.7853981633974483


## **Angles of Each Value in Arrays**

In [109]:
arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


## **Hypotenues**

Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the **hypot()** function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.



In [110]:
base = 3
perp = 4

hyp = np.hypot(base, perp)

print(hyp)

5.0




---



# **Hyperbolic Functions**

NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values..

In [111]:
x = np.sinh(np.pi/2)

print(x)

2.3012989023072947


In [112]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


## **Finding Angles**

Finding angles from values of hyperbolic sine, cos, tan. E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.

In [113]:
x = np.arcsinh(1.0)

print(x)


0.881373587019543



## **Angles of Each Value in Arrays**


In [114]:
arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

[0.10033535 0.20273255 0.54930614]




---



# **Set Operations**

A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

## **Create Sets in NumPy**

We can use NumPy's **unique()** method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

In [115]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


## **Finding Union**

To find the unique values of two arrays, use the **union1d()** method.



In [116]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


## **Finding Intersection**

To find only the values that are present in both arrays, use the **intersect1d()** method.

In [117]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


**Note:** the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

## **Finding Difference**

To find only the values in the first set that is NOT present in the seconds set, use the **setdiff1d()** method.

In [118]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


**Note:** the setdiff1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

# **Finding Symmetric Difference**

To find only the values that are NOT present in BOTH sets, use the **setxor1d()** method.



In [119]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]


**Note:** the setxor1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.